services:
  postgresql:
    image: postgres:16-alpine
    container_name: oneqit_postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
    volumes:
      - oneqit-postgresql-data:/var/lib/postgresql/data
    networks:
      - network_oneqit
    restart: unless-stopped

volumes:
  oneqit-postgresql-data:

networks:
  network_oneqit:
    driver: bridge
