services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: oneqit_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    depends_on:
      - postgresql
    networks:
      - network_oneqit
    restart: unless-stopped
