services:
  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: oneqit_rabbitmq
    ports:
      - "5672:5672"
    networks:
      - oneqit-rabbitmq-network
    restart: unless-stopped

networks:
  oneqit-rabbitmq-network:
    driver: bridge
