services:
  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: oneqit_rabbitmq
    ports:
      - "5672:5672"
    networks:
      - network_oneqit
    restart: unless-stopped

networks:
  network_oneqit:
    driver: bridge
