services:
  mongo-express:
    image: mongo-express:latest
    container_name: oneqit_mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:-}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-}
      ME_CONFIG_BASICAUTH: ${ME_BASICAUTH_ENABLED:-false}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_BASICAUTH_USERNAME:-}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_BASICAUTH_PASSWORD:-}
    depends_on:
      - mongodb
    networks:
      - mongodb-network
    restart: unless-stopped
