services:
  kibana:
    image: kibana:8.12.0
    container_name: oneqit_kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: ${ELASTIC_USERNAME:-}
      ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD:-}
    depends_on:
      - elasticsearch
    networks:
      - oneqit-elasticsearch-network
    restart: unless-stopped
