services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: oneqit_kafka_ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL:-}
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM:-}
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: ${KAFKA_SASL_JAAS_CONFIG:-}
    depends_on:
      - kafka
    networks:
      - kafka-network
    restart: unless-stopped
