services:
  redis:
    image: redis:7-alpine
    container_name: oneqit_redis
    ports:
      - "6379:6379"
    networks:
      - network_oneqit
    restart: unless-stopped

networks:
  network_oneqit:
    driver: bridge
